# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-file", "~> 0.8.0"

gem "colorize", "~> 0.8.1"

gem "tty-prompt", "~> 0.21.0"

gem "tty-table", "~> 0.11.0"

gem "artii", "~> 2.1"
